### ISSUE TITLE
Error: Server took too long to start

### ISSUE THREAD

**Issue by bitsnaps** [KillianLucas/ooba#10]
Hi, Running on Colab with T4 GPU and [Gitpod](https://gitpod.io/) ends with the following message:
```
Getting started...
Server took too long to start

---------------------------------------------------------------------------

Exception                                 Traceback (most recent call last)

[/usr/local/lib/python3.10/dist-packages/ooba/llm.py](https://localhost:8080/#) in __init__(self, path, cpu, verbose, first_time)
    104             else:
--> 105                 raise Exception("Server took too long to start")
    106 

Exception: Server took too long to start


During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)

2 frames

[/usr/local/lib/python3.10/dist-packages/ooba/llm.py](https://localhost:8080/#) in __init__(self, path, cpu, verbose, first_time)
    103                     time.sleep(1.5)
    104             else:
--> 105                 raise Exception("Server took too long to start")
    106 
    107 

Exception: Server took too long to start
```
The model `dolphin-2.6-mixtral-8x7b-GGUF`is really big, but it worked in webui, this issue is also known at [open-interpreter](https://github.com/KillianLucas/open-interpreter/issues/640), is there any timeout param to increase?
Another issue GPU is not detected, it falls back to CPU on Colab.

**Comment by Notnaton** [comment]
Hi, to fix this you need my patches found at: https://github.com/Notnaton/ooba

If you are using Open-interpreter:
Open-interpreter haven't used ooba for a long time. Please update Open-interpreter if possible `pip install Open-interpreter --force-reinstall` 

Simply use `interpreter --api_base http://localhost:port/v1 --model openai/local --api_key dummykey` to connect to Oobabooga  once interpreter is updated.

**Comment by bitsnaps** [comment]
@Notnaton 
The patch is for Windows? trying on colab ends with:
```
FileNotFoundError: [Errno 2] No such file or directory: '--cpu'
```

**Comment by Notnaton** [comment]
It was originally for windows but it works for all systems.

This is quite outdated, so I don't know if it currently works

**Comment by Notnaton** [comment]
No such file or directory... Seems like some stuff has changed for it to try to open --cpu as a file/directory 

Could you share how you launch it?

**Comment by bitsnaps** [comment]
> No such file or directory... Seems like some stuff has changed for it to try to open --cpu as a file/directory
> 
> Could you share how you launch it?

Just like you wrote in `README.md`, actually I tried both ways, it's been a while... it ok never mind, I'll be trying the API from [webui](https://github.com/oobabooga/text-generation-webui/blob/main/docs/12%20-%20OpenAI%20API.md).
