### ISSUE TITLE
login in install_oobagooba.py for wsl doesn't work imo

### ISSUE THREAD

**Issue by merlinfrombelgium** [KillianLucas/ooba#2]
So since #1 is just sitting there, I'm giving WSL2 on Win11 a go.

It falls over and I think I see why.

```
if system == "Linux":
        if "microsoft" in platform.uname().release.lower():
            self.start_script = os.path.join(REPO_DIR, "start_wsl.bat")
```

We can't run a .bat script from WSL 😊 
Since the script basically calls wsl and runs wsl.sh, I chose to run that manually and all ran smoothly!

**Comment by merlinfrombelgium** [comment]
Just adding to this for extra info. I just updated to OI 0.1.9 using pip, bot in Windows and WSL2. In the latter, running `interpreter --local` failed because it tries to run a .bat file

![image](https://github.com/KillianLucas/ooba/assets/26247323/2806d08e-b9d4-4f36-8b5b-dfb11b7826ea)

**Comment by ZackBradshaw** [comment]
I'm having this same issue
